const ACTION_TYPES = {
  GET_LOGIN_EMAIL_PASSWORD: 'GET_LOGIN_EMAIL_PASSWORD',
  SET_LOGIN_EMAIL_PASSWORD: 'SET_LOGIN_EMAIL_PASSWORD',
  ERROR_LOGIN_EMAIL_PASSWORD: 'ERROR_LOGIN_EMAIL_PASSWORD',
  GET_REGISTER_EMAIL_PASSWORD: 'GET_REGISTER_EMAIL_PASSWORD',
  SET_REGISTER_EMAIL_PASSWORD: 'SET_REGISTER_EMAIL_PASSWORD',
  ERROR_REGISTER_EMAIL_PASSWORD: 'ERROR_REGISTER_EMAIL_PASSWORD',
  GET_LOGIN_GOOGLE_AUTH: 'GET_LOGIN_GOOGLE_AUTH',
  GET_REGISTER_GOOGLE_AUTH: 'GET_LOGIN_GOOGLE_AUTH',
  START_SAVING_NOTES:'START_SAVING_NOTES',
  GET_SAVE_NOTES: 'GET_SAVE_NOTES',
  SET_SAVE_NOTES: 'SET_SAVE_NOTES',
  ERROR_SAVE_NOTES: 'ERROR_SAVE_NOTES',
  START_FETCHING_NOTES: 'START_FETCHING_NOTES',
  GET_SAVED_NOTES: 'GET_SAVED_NOTES',
  SET_SAVED_NOTES: 'SET_SAVED_NOTES',
  ERROR_SAVED_NOTES: 'ERROR_SAVED_NOTES',
}

export {
    ACTION_TYPES,
}