const ACTION_TYPES = {
  GET_LOGIN_EMAIL_PASSWORD: 'GET_LOGIN_EMAIL_PASSWORD',
  SET_LOGIN_EMAIL_PASSWORD: 'SET_LOGIN_EMAIL_PASSWORD',
  ERROR_LOGIN_EMAIL_PASSWORD: 'ERROR_LOGIN_EMAIL_PASSWORD',
  GET_REGISTER_EMAIL_PASSWORD: 'GET_REGISTER_EMAIL_PASSWORD',
  SET_REGISTER_EMAIL_PASSWORD: 'SET_REGISTER_EMAIL_PASSWORD',
  ERROR_REGISTER_EMAIL_PASSWORD: 'ERROR_REGISTER_EMAIL_PASSWORD',
}

export {
    ACTION_TYPES,
}